### ISSUE TITLE
react-native-gesture-handler:compileDebugJavaWithJavac FAILED with react-native 0.60.0

### ISSUE THREAD

**Issue by viveknaragude** [kmagiera/react-native-gesture-handler#670]
React-native 0.60.0 is release, they added Autolinking of package feature 
![image](https://user-images.githubusercontent.com/25178257/60686280-76c6d980-9ec5-11e9-8fcc-28b42a5c8ddd.png)

Ref : https://github.com/react-native-community/releases/blob/master/CHANGELOG.md

**Comment by nidelson** [comment]
Same problem.

RNGestureHandlerEvent.java:3: error: package android.support.v4.util does not exist
> import android.support.v4.util.Pools;

**Comment by vokhuyetOz** [comment]
you should use react-native 0.59.10, this project needs to migrate to androidX, now it doesn't work with react-native 0.60

**Comment by TSjianjiao** [comment]
you can search the jetifier in github

**Comment by viveknaragude** [comment]
@TSjianjiao 
It not work same error

**Current Behavior**
After running react-native run-android shows :
null is not an object (evaluating 'RNGestureHandlerModule.State'. )

**Comment by localnet** [comment]
As React Native implements autolink, you need unlink native dependencies previously linked. [Documentation](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md):

> Autolinking is a replacement for react-native link. If you have been using React Native before version 0.60, please unlink native dependencies if you have any from a previous install.

And for AndroidX at now you can use this [workaround](https://stackoverflow.com/a/56323107/10798494).
